// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 

#include ".pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

void InitDefaults_() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_ = nullptr;
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_ = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_ = nullptr;
const ::google::protobuf::uint32 TableStruct_::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = nullptr;
static constexpr ::google::protobuf::Message* const* file_default_instances = nullptr;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_ = {
  {}, AddDescriptors_, "", schemas,
  file_default_instances, TableStruct_::offsets,
  file_level_metadata_, 0, file_level_enum_descriptors_, file_level_service_descriptors_,
};

const char descriptor_table_protodef_[] =
  "\n\000"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_ = {
  false, InitDefaults_, 
  descriptor_table_protodef_,
  "", &assign_descriptors_table_, 2,
};

void AddDescriptors_() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ = []() { AddDescriptors_(); return true; }();

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
